experimentName: Rank
trialCommand: python src/main.py experiment=mdora dataset=mmimdb EXP_NOTE=nni hparams_search=nni train.PRINT_FREQ=1000 train.BATCH_SIZE=256
trialConcurrency: 4
maxTrialNumber: 1000
searchSpaceFile: search_space.json
trialCodeDirectory: ../../../
trialGpuNumber: 1
tuner:
  name: GridSearch
trainingService:
  platform: local
  useActiveGpu: True